
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessBookWebApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sale
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sale()
    {

        this.SaleDetail = new HashSet<SaleDetail>();

    }


    public int SaleId { get; set; }

    public System.DateTime DateCreation { get; set; }

    public string CodeGuide { get; set; }

    public Nullable<int> LocalId { get; set; }

    public double PriceTotal { get; set; }

    public int EmployeeId { get; set; }

    public Nullable<int> ClientId { get; set; }

    public string State { get; set; }

    public string StateDelivery { get; set; }



    public virtual Client Client { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Local Local { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SaleDetail> SaleDetail { get; set; }

}

}
